import type { SenStatsCommitteeDocument, SenStatsExpenseDocument, SenStatsSenatorDocument } from '../../types';
import { currency } from './SenStatsHelpers';

interface SenStatsDataSourcesViewProps {
  senatorCount: number;
  selectedSenator?: SenStatsSenatorDocument;
  expenses: Array<SenStatsExpenseDocument & { id: string }>;
  committees: Array<SenStatsCommitteeDocument & { id: string }>;
}

const officialSources = [
  { label: 'Current senators roster', url: 'https://sencanada.ca/umbraco/surface/SenatorsAjax/GetSenators?Lang=en&displayFor=senatorslist' },
  { label: 'Open North Represent fallback', url: 'https://represent.opennorth.ca/representatives/senate/?limit=1000' },
  { label: 'Senate proactive disclosure summary', url: 'https://sencanada.ca/en/ProActive/Summary' },
  { label: 'Senate proactive disclosure details', url: 'https://sencanada.ca/en/ProActive/Summary/Details' },
  { label: 'Senate committees directory', url: 'https://sencanada.ca/en/committees/' },
];

const fieldSources = [
  { field: 'Name, province, group', source: 'Official Senate current-senators roster, with Open North Represent as a fallback/enrichment source.', firestorePath: 'senstats_senators/{senatorId}' },
  { field: 'Office details', source: 'Official Senate roster cells such as nominated date, retirement date, and appointed-on-advice-of details.', firestorePath: 'senstats_senators/{senatorId}.officeDetails' },
  { field: 'Photo / thumbnail', source: 'Official Senate senator profile page image or profile og:image metadata.', firestorePath: 'senstats_senators/{senatorId}.photoUrl' },
  { field: 'Profile links and contact details', source: 'Official Senate senator profile page links, mailto/tel links, tables, and definition lists.', firestorePath: 'senstats_senators/{senatorId}.profileDetails / contactDetails' },
  { field: 'Quarterly expenses', source: 'Senate ProActive Summary, Summary Details, and discovered linked disclosure pages or CSV files.', firestorePath: 'senstats_senators/{senatorId}/expenses/{expenseId}' },
  { field: 'Committee membership', source: 'Senate committee pages discovered from the public committees directory.', firestorePath: 'senstats_committees/{committeeId}' },
  { field: 'Affiliation history', source: 'Generated by the sync when a senator document group changes between runs.', firestorePath: 'senstats_senators/{senatorId}/party_affiliation_history/{historyId}' },
];

export function SenStatsDataSourcesView({ senatorCount, selectedSenator, expenses, committees }: SenStatsDataSourcesViewProps) {
  const expenseTotal = expenses.reduce((sum, expense) => sum + Number(expense.amount || 0), 0);
  const expenseSourceUrls = Array.from(new Set(expenses.map((expense) => expense.sourceUrl).filter(Boolean))).slice(0, 5) as string[];
  const selectedPhotoUrl = selectedSenator?.photoUrl || (typeof selectedSenator?.profileDetails?.photoUrl === 'string' ? selectedSenator.profileDetails.photoUrl : '');

  return (
    <section className="data-sources-view" aria-label="SenStats data sources">
      <div className="source-overview-grid">
        <article className="source-card primary">
          <span>Selected senator</span>
          <strong>{selectedSenator?.name ?? 'No senator selected'}</strong>
          <small>{selectedSenator?.sourceUrl ? 'Official profile linked' : 'Profile source not available yet'}</small>
          {selectedSenator?.sourceUrl && <a href={selectedSenator.sourceUrl} target="_blank" rel="noreferrer">Open source profile</a>}
        </article>
        <article className="source-card">
          <span>Senators synced</span>
          <strong>{senatorCount}</strong>
          <small>Stored in <code>senstats_senators</code></small>
        </article>
        <article className="source-card">
          <span>Selected expenses</span>
          <strong>{currency(expenseTotal)}</strong>
          <small>{expenses.length} records for current senator</small>
        </article>
        <article className="source-card">
          <span>Committees</span>
          <strong>{committees.length}</strong>
          <small>Stored in <code>senstats_committees</code></small>
        </article>
      </div>

      <div className="source-card source-wide">
        <div className="source-heading"><span>Official public sources</span><strong>What the sync reads</strong></div>
        <div className="source-link-list">
          {officialSources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer"><span>{source.label}</span><small>{source.url}</small></a>)}
        </div>
      </div>

      <div className="source-card source-wide">
        <div className="source-heading"><span>Field-level provenance</span><strong>Where each piece of data comes from</strong></div>
        <div className="source-table" role="table" aria-label="Field-level SenStats data provenance">
          <div role="row" className="source-table-head"><span role="columnheader">Data</span><span role="columnheader">Source</span><span role="columnheader">Firestore path</span></div>
          {fieldSources.map((item) => <div role="row" key={item.field}><strong role="cell">{item.field}</strong><span role="cell">{item.source}</span><code role="cell">{item.firestorePath}</code></div>)}
        </div>
      </div>

      <div className="source-card source-wide">
        <div className="source-heading"><span>Current senator document</span><strong>Stored source fields</strong></div>
        <div className="source-field-grid">
          <p><span>Document id</span><code>{selectedSenator?.id ?? '—'}</code></p>
          <p><span>Profile URL</span>{selectedSenator?.sourceUrl ? <a href={selectedSenator.sourceUrl} target="_blank" rel="noreferrer">{selectedSenator.sourceUrl}</a> : <small>Not synced</small>}</p>
          <p><span>Photo URL</span>{selectedPhotoUrl ? <a href={selectedPhotoUrl} target="_blank" rel="noreferrer">{selectedPhotoUrl}</a> : <small>Not synced</small>}</p>
          <p><span>Raw API/Senate payload</span><code>{selectedSenator?.rawData ? 'rawData saved' : 'No rawData field yet'}</code></p>
        </div>
      </div>

      <div className="source-card source-wide">
        <div className="source-heading"><span>Expense provenance</span><strong>Source URLs found for selected senator</strong></div>
        {expenseSourceUrls.length ? <div className="source-link-list compact">{expenseSourceUrls.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer"><span>Expense source</span><small>{url}</small></a>)}</div> : <p className="muted">No expense source URLs are stored for the selected senator yet. Rerun the SenStats sync after deploying the latest scraper changes.</p>}
      </div>
    </section>
  );
}
