name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: AIzaSyCp1HdSHYQXE-yY8ga6alvLv2gka2d9Ltw
          VITE_FIREBASE_AUTH_DOMAIN: quorum-2.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID: quorum-2
          VITE_FIREBASE_STORAGE_BUCKET: quorum-2.firebasestorage.app
          VITE_FIREBASE_MESSAGING_SENDER_ID: '594173636153'
          VITE_FIREBASE_APP_ID: '1:594173636153:web:cf3c1d2aadde06508167e8'
          VITE_FIREBASE_MEASUREMENT_ID: G-PLLC7GDQMM


      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: quorum-2
          channelId: live
